// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class ASSERTEDITAL642019Test {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void aSSERTEDITAL642019() {
    driver.get("https://ifrs.edu.br/");
    driver.manage().window().setSize(new Dimension(699, 728));
    js.executeScript("window.scrollTo(0,2235)");
    js.executeScript("window.scrollTo(0,3390)");
    js.executeScript("window.scrollTo(0,5216)");
    {
      WebElement element = driver.findElement(By.cssSelector(".wp-image-44299"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.cssSelector(".acesso-todos-editais__link")).click();
    driver.findElement(By.cssSelector("#DataTables_Table_0_filter .form-control")).click();
    driver.findElement(By.cssSelector("#DataTables_Table_0_filter .form-control")).sendKeys("64/2019");
    driver.findElement(By.linkText("EDITAL IFRS Nº 64/2019 FOMENTO INTERNO PARA PROJETOS DE PESQUISA E INOVAÇÃO 2020/2021")).click();
    {
      List<WebElement> elements = driver.findElements(By.cssSelector(".edital__title"));
      assert(elements.size() > 0);
    }
  }
}
